#!/bin/bash

#
# Infomaniak SwissTransfer - Multiplatform
# Copyright (C) 2024 Infomaniak Network SA
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Variables
bold=$(tput bold)
endBold=$(tput sgr0)

# Scripts
echo "${bold}Start cleanAll Task${endBold}"
./gradlew cleanAll
echo "${bold}cleanAll task completed.${endBold}"

echo "${bold}Start assembleDBReleaseXCFramework Task${endBold}"
./gradlew :STDatabase:assembleSTDatabaseReleaseXCFramework
echo "${bold}cleanAll task completed.${endBold}"

echo "${bold}Start assembleNetworkReleaseXCFramework Task${endBold}"
./gradlew :STNetwork:assembleSTNetworkReleaseXCFramework
echo "${bold}cleanAll task completed.${endBold}"

echo "${bold}Start assembleCoreReleaseXCFramework Task${endBold}"
./gradlew :STCore:assembleSTCoreReleaseXCFramework
echo "${bold}cleanAll task completed.${endBold}"
