name: Multiplatform CI

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  tests:
    if: github.event.pull_request.draft == false
    runs-on: [ self-hosted, Android ]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout the code
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ github.token }}
          submodules: recursive

      # Setup Gradle and clean
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean

      # Run tests
      # We run each test independently instead of `allTests` because we have a concurrency problem on Realm
      - name: Run Android Unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Run iOS Unit tests
        run: ./gradlew iosSimulatorArm64Test --stacktrace

#      - name: Run Unit tests
#        run: ./gradlew allTests --stacktrace
